; Alpine GPS — PlatformIO Configuration
; RP2040-Zero with Pico SDK (no Arduino)

[platformio]
default_envs = rp2040zero
src_dir = FW/src
include_dir = FW/include
lib_dir = FW/lib

[env:rp2040zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.core = earlephilhower
board_build.f_cpu = 133000000L
build_flags =
    -I FW/include
    -DCFG_TUSB_MCU=OPT_MCU_RP2040
    -DUSE_TINYUSB
    -Dtimegm=mktime
    -std=gnu17
build_unflags = -std=gnu++11
lib_ldf_mode = deep+
